version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${VEHICLE_INVENTORY_SERVER_PORT}:${VEHICLE_INVENTORY_SERVER_PORT}'
    volumes:
      - ./:/usr/src/app